name: Auto move JS files to /plugins

on:
  push:
    branches: [ main ]        # bisa ubah ke branch lain
  workflow_dispatch:          # bisa run manual

permissions:
  contents: write
  pull-requests: write

jobs:
  move-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Move all .js files to /plugins
        run: |
          mkdir -p plugins

          echo "== Before move =="
          ls -lah

          # cari semua file .js di root dan subfolder kecuali /plugins itu sendiri
          find . -type f -name "*.js" ! -path "./plugins/*" -print -exec mv -f {} plugins/ \;

          echo "== After move =="
          ls -lah plugins || true

      - name: Commit and push changes
        id: commitpush
        continue-on-error: true
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          if git diff --cached --quiet; then
            echo "No .js files moved, nothing to commit."
            exit 0
          fi
          git commit -m "Auto-move all .js files to /plugins folder"
          git push origin HEAD:main

      - name: Fallback via PR (if main protected)
        if: steps.commitpush.outcome == 'failure'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Auto-move all .js files to /plugins folder"
          title: "Auto-move JS → plugins"
          body: "Branch main dilindungi, dibuat PR otomatis oleh workflow."
          branch: movejs-auto/${{ github.run_id }}
          delete-branch: true
